### ISSUE TITLE
API endpoints

### ISSUE THREAD

**Issue by pokhrelkay** [secmohammed/single-tenant#1]
How do we serve API endpoints in this case?

**Comment by secmohammed** [comment]
you can apply the normal configuration that Laravel provides for api routes at your RouteServiceProvider, copy the prefix, and the middleware then assign them to the tenant Routes, and I believe that's pretty much it

```
protected function mapTenantRoutes() {
		Route::prefix('api')
                        ->middleware('api', 'tenant', 'bindings')
			->namespace("{$this->namespace}\Tenant")
			->group(base_path('routes/tenant.php'));
	}

```

then you can start sending json responses, and since the tenant routes have api middleware applied , responses will be jsonified automatically.

**Comment by pokhrelkay** [comment]
Thank you that you replied. I am having hard time inplementing this with
passport. I need web as well as api. Can you please give me some quick
guideline how to integrate this with passport.

**Comment by secmohammed** [comment]
You can apply whatever Middleware you like at the provider,  but I think you wouldn't need a Web Middleware while using the passport, can you please provide more details about what's happening,  or show a snippet
